#!/bin/bash

echo "🔍 Diagnosing 'Client is public' Error"
echo "========================================"
echo ""

echo "This error means Azure thinks your app is a PUBLIC client,"
echo "but your code is using it as a CONFIDENTIAL client (with secret)."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "CRITICAL: Check Azure Portal Settings"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Go to: Azure Portal → Azure AD → App registrations → Your App"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Check Redirect URIs (You've done this)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click: Authentication (left menu)"
echo ""
echo "Under 'Platform configurations':"
echo "  ✅ Web"
echo "     └─ http://localhost:5001/auth/callback"
echo ""
echo "  ⚠️  If you also see 'Mobile and desktop applications':"
echo "     You can leave it OR remove the redirect URI from there"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Disable Public Client Flows (CRITICAL!)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Scroll down on the same 'Authentication' page to:"
echo ""
echo "┌─────────────────────────────────────────────────────────┐"
echo "│ Advanced settings                                       │"
echo "│                                                         │"
echo "│ Allow public client flows                              │"
echo "│ Enable the following mobile and desktop flows:         │"
echo "│                                                         │"
echo "│ ⚠️  CURRENT (causing error):                            │"
echo "│     ● Yes  ← WRONG FOR SERVER APPS                     │"
echo "│     ○ No                                                │"
echo "│                                                         │"
echo "│ ✅ MUST CHANGE TO:                                      │"
echo "│     ○ Yes                                               │"
echo "│     ● No   ← SELECT THIS FOR SERVER APPS               │"
echo "│                                                         │"
echo "└─────────────────────────────────────────────────────────┘"
echo ""
echo "Then click: [Save]"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Verify Client Secret Exists"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click: Certificates & secrets (left menu)"
echo ""
echo "Under 'Client secrets' tab:"
echo "  ✅ Should have at least one active (not expired) secret"
echo ""
echo "  If NOT, or if expired:"
echo "    1. Click: + New client secret"
echo "    2. Description: 'Production Secret'"
echo "    3. Expires: Choose duration (24 months recommended)"
echo "    4. Click: Add"
echo "    5. ⚠️  COPY THE VALUE IMMEDIATELY (won't show again!)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Update .env with Secret VALUE (not ID)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In your .env file, make sure you have the secret VALUE:"
echo ""
echo "MICROSOFT_CLIENT_SECRET=ABC~defGHI123jklMNO456~pqrSTU789"
echo "                         ↑"
echo "                         This should be ~40 characters"
echo "                         with special chars like ~ or ."
echo ""
echo "❌ WRONG (this is the secret ID, not VALUE):"
echo "   MICROSOFT_CLIENT_SECRET=12345678-1234-1234-1234-123456789abc"
echo ""
echo "✅ CORRECT (this is the secret VALUE):"
echo "   MICROSOFT_CLIENT_SECRET=abc~123.DEF456ghi~789JKL"
echo ""

# Check current .env
if [ -f .env ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "YOUR CURRENT .env CONFIGURATION"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    
    SECRET=$(grep "^MICROSOFT_CLIENT_SECRET=" .env 2>/dev/null | cut -d '=' -f2- | tr -d '"' | tr -d "'")
    
    if [ -z "$SECRET" ]; then
        echo "❌ MICROSOFT_CLIENT_SECRET: NOT SET"
        echo "   You must add this to your .env file!"
    else
        SECRET_LEN=${#SECRET}
        echo "✅ MICROSOFT_CLIENT_SECRET: Set (length: $SECRET_LEN chars)"
        echo "   First 10 chars: ${SECRET:0:10}..."
        echo ""
        
        if [ $SECRET_LEN -lt 30 ]; then
            echo "⚠️  WARNING: Secret seems too short ($SECRET_LEN chars)"
            echo "   Typical secret is 40+ characters"
            echo "   You might have the secret ID instead of VALUE"
        elif echo "$SECRET" | grep -qE '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'; then
            echo "❌ ERROR: This looks like a GUID/UUID (secret ID)"
            echo "   You need the secret VALUE, not the ID!"
            echo "   Go to Azure Portal → Certificates & secrets"
            echo "   Create a NEW secret and copy the VALUE"
        else
            echo "✅ Secret format looks correct (has special chars, right length)"
        fi
    fi
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Restart App"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After making changes:"
echo ""
echo "  ./start_fresh.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6: Test Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check if app is running with correct config:"
echo ""
echo "  curl http://localhost:5001/debug/msal-config | python3 -m json.tool"
echo ""
echo "Should show:"
echo "  - client_secret_set: true"
echo "  - client_secret_length: 40+ "
echo ""

if curl -s http://localhost:5001/debug/msal-config > /dev/null 2>&1; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "CURRENT APP CONFIGURATION"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    curl -s http://localhost:5001/debug/msal-config | python3 -m json.tool
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SUMMARY: What You Need to Do"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Azure Portal changes:"
echo "  1. ✅ Authentication → Platform: Web (you did this)"
echo "  2. ⚠️  Authentication → Advanced settings → Allow public client flows: NO"
echo "  3. ✅ Certificates & secrets → Ensure you have active secret"
echo ""
echo ".env file changes:"
echo "  1. ⚠️  MICROSOFT_CLIENT_SECRET must be the VALUE (40+ chars with special chars)"
echo "  2. ⚠️  NOT the secret ID (GUID format)"
echo ""
echo "After changes:"
echo "  ./start_fresh.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
